name: Server Pull Request

on:
  pull_request:
    paths: [".github/workflows/server**", ".eslintrc.js", "server/**"]

jobs:
  pull_request:
    name: Server Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Tests
        run: npm run test:cov:server
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: server
      - name: E2E Tests
        run: npm run test:e2e:server
      - name: Build
        run: npm run build
