name: Web App Pull Request

on:
  pull_request:
    paths: [".github/workflows/web-app**", ".eslintrc.js", "common/**", "web-app/**"]

jobs:
  pull_request:
    name: Web-App Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Tests
        run: npm run test:cov:web-app
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: web-app
